#ifndef ACTUATOR_PINS_H
#define ACTUATOR_PINS_H

#define DIGITAL_OUTPUT_RELAY1_PIN 16
#define DIGITAL_OUTPUT_RELAY2_PIN 17

#define DIGITAL_OUTPUT_RELAY1_NAME "relay1"
#define DIGITAL_OUTPUT_RELAY2_NAME "relay2"

#endif // ACTUATOR_PINS_H