#ifndef APP_ERRORS_ENUMERATION_H
#define APP_ERRORS_ENUMERATION_H

enum class AppErrors {
    ERR_INIT_INPUT_MANAGER,
    ERR_INIT_SENSOR_MANAGER,
    ERR_INIT_DISPLAY_MANAGER,
    ERR_INIT_ACTUATOR_MANAGER,
    ERR_INIT_PROCESS_MANAGER,
    ERR_INIT_NETWORK_MANAGER,
    ERR_INIT_TIME_MANAGER,
};

#endif // APP_ERRORS_ENUMERATION_H
