#ifndef APP_STATES_ENUMERATION_H
#define APP_STATES_ENUMERATION_H

enum class AppStates {
    STARTING_UP,
    SYSTEM_IN_ERROR,
    INITIALIZING,
    IDLING,
    INFORMING,
    SETTING_PROCESS,
    RUNNING,
    ABORTING,
    DIAGNOSING,
};

#endif // APP_STATES_ENUMERATION_H
