#ifndef INPUT_PINS_H
#define INPUT_PINS_H

#define BUTTON_BACK_PIN 12
#define ROTARY_ENCODER_MAIN_A_PIN 18
#define ROTARY_ENCODER_MAIN_B_PIN 19
#define ROTARY_ENCODER_MAIN_BUTTON_PIN 21

#endif // INPUT_PINS_H